

Avahi = { };


Avahi.SERVER_INVALID = 0;
Avahi.SERVER_REGISTERING = 1;
Avahi.SERVER_RUNNING = 2;
Avahi.SERVER_COLLISION = 3;
Avahi.SERVER_FAILURE = 4

Avahi.ENTRY_GROUP_UNCOMMITED = 0
Avahi.ENTRY_GROUP_REGISTERING = 1
Avahi.ENTRY_GROUP_ESTABLISHED = 2
Avahi.ENTRY_GROUP_COLLISION = 3
Avahi.ENTRY_GROUP_FAILURE = 4

Avahi.DOMAIN_BROWSER_BROWSE = 0
Avahi.DOMAIN_BROWSER_BROWSE_DEFAULT = 1
Avahi.DOMAIN_BROWSER_REGISTER = 2
Avahi.DOMAIN_BROWSER_REGISTER_DEFAULT = 3
Avahi.DOMAIN_BROWSER_BROWSE_LEGACY = 4

Avahi.PROTO_UNSPEC = -1
Avahi.PROTO_INET = 0
Avahi.PROTO_INET6 = 1

Avahi.IF_UNSPEC = -1

Avahi.PUBLISH_UNIQUE = 1
Avahi.PUBLISH_NO_PROBE = 2
Avahi.PUBLISH_NO_ANNOUNCE = 4
Avahi.PUBLISH_ALLOW_MULTIPLE = 8
Avahi.PUBLISH_NO_REVERSE = 16
Avahi.PUBLISH_NO_COOKIE = 32
Avahi.PUBLISH_UPDATE = 64
Avahi.PUBLISH_USE_WIDE_AREA = 128
Avahi.PUBLISH_USE_MULTICAST = 256

Avahi.LOOKUP_USE_WIDE_AREA = 1
Avahi.LOOKUP_USE_MULTICAST = 2
Avahi.LOOKUP_NO_TXT = 4
Avahi.LOOKUP_NO_ADDRESS = 8

Avahi.LOOKUP_RESULT_CACHED = 1
Avahi.LOOKUP_RESULT_WIDE_AREA = 2
Avahi.LOOKUP_RESULT_MULTICAST = 4
Avahi.LOOKUP_RESULT_LOCAL = 8
Avahi.LOOKUP_RESULT_OUR_OWN = 16
Avahi.LOOKUP_RESULT_STATIC = 32


Avahi.Namespace = "org.freedesktop.Avahi";
Avahi.Server = "org.freedesktop.Avahi.Server";
Avahi.EntryGroup = "org.freedesktop.Avahi.EntryGroup";
Avahi.ServiceBrowser = "org.freedesktop.Avahi.ServiceBrowser";


module.exports = Avahi;